export const vaccins = [
  {
    id: 0,
    nom: 'BBIBP-CorV',
    inventeurs: [
      'Sinopharm',
    ],
    lieux: [
      'Chine',
    ],
    technologie: 'virus inactivé',
    quantite: 420,
    prix: 17,
    approuve: true,
    image: 'bbibp-corv.jpg',
  },
  {
    id: 1,
    nom: 'Sputnik V',
    inventeurs: [
      'Gamaleya',
    ],
    lieux: [
      'Russie',
      'Inde',
    ],
    technologie: 'Adenovirus',
    quantite: 130,
    prix: 12,
    approuve: false,
    image: 'sputnik-v.jpg',
  },
  {
    id: 2,
    nom: 'AZD1222',
    inventeurs: [
      'AstraZeneca',
      'University of Oxford',
    ],
    lieux: [
      'Royaume Unis',
      'Brésil',
      'Inde',
    ],
    technologie: 'adenovirus',
    quantite: 5028,
    prix: 1.78,
    approuve: false,
    image: 'azd1222.jpg',
  },
  {
    id: 3,
    nom: 'Tozinameran',
    inventeurs: [
      'BioNTech',
      'Pfizer',
      'Fosun Pharma',
    ],
    lieux: [
      'Allemagne',
      'USA',
    ],
    technologie: 'ARN messager',
    quantite: 980,
    prix: 14,
    approuve: true,
    image: 'tozinameran.jpg',
  },
  {
    id: 4,
    nom: 'mRNA-1273',
    inventeurs: [
      'Moderna',
      'NIAID',
      'BARDA',
    ],
    lieux: [
      'USA',
    ],
    technologie: 'ARN messager',
    quantite: 240,
    prix: 28,
    approuve: false,
    image: 'mrna-1273.jpg',
  },
  {
    id: 5,
    nom: 'Ad26.COV2.S',
    inventeurs: [
      'Johnson & Johnson',
      'BIDMC',
    ],
    lieux: [
      'USA',
      'Amérique du Sud',
      'Ukraine',
      'Afrique du Sud',
    ],
    technologie: 'adenovirus',
    quantite: 110,
    prix: 31,
    approuve: false,
    image: 'ad26-cov2-s.jpg',
  },
];
